FROM cseelye/linux-shell:latest

ARG VCS_REF=unknown
ARG BUILD_DATE=unknown
ARG VERSION=0.0
LABEL maintainer="cseelye@gmail.com" \
      url="https://github.com/cseelye/docker-linux-shell" \
      name="docker-linux-shell-x11" \
      description="Interactive linux shell" \
      vcs-ref=$VCS_REF \
      build-date=$BUILD_DATE \
      version=$VERSION

ENV TERM=xterm-color

# Virtualization UIs
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes \
        virt-manager \
        virt-viewer && \
    apt-get autoremove --assume-yes && \
    apt-get clean && \
    rm --force --recursive /var/lib/apt/lists/* /tmp/* /var/tmp/*

# kdiff3 - put into its own layer because it is so huge
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install kdiff3 && \
    apt-get autoremove --assume-yes && \
    apt-get clean && \
    rm --force --recursive /var/lib/apt/lists/* /tmp/* /var/tmp/*

# ClusterSSH and perl stuff
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install \
        libpng-dev \
        libterm-readline-gnu-perl \
        libx11-dev \
        xterm && \
    (echo y;echo o conf prerequisites_policy follow;o conf build_cache 50;echo o conf commit) | cpan  && \
    ln -s /bin/tar /usr/bin/tar && \
    ln -s /bin/gzip /usr/bin/gzip && \
    cpan -f install CPAN::WAIT CPAN::Changes Exception::Class Readonly Test::DistManifest Test::PerlTidy Test::Pod::Coverage Tk App::ClusterSSH && \
    apt-get autoremove --assume-yes && \
    apt-get clean && \
    rm --force --recursive /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cpan/build/* /root/.cpan/rouces/authors/id

CMD ["/bin/bash"]
