#!/bin/bash
set -euo pipefail

# Additional options to the docker run command - https://docs.docker.com/engine/reference/commandline/run/
LINUX_SHELL_RUN_OPTIONS=${LINUX_SHELL_RUN_OPTIONS:-}

# The base docker image to use for shells
LINUX_SHELL_IMAGE_NAME=${LINUX_SHELL_IMAGE_NAME:-cseelye/linux-shell}

# The name to give to shell container instances
LINUX_SHELL_CONTAINER_NAME="linux-shell-"

# Path to an explicit docker binary. Leave blank to auto-discover
DOCKER_BINARY=${DOCKER_BINARY-}



# Parse command line options
SHARED=0
while getopts ":srp" opt; do
    case ${opt} in
        s)
            SHARED=1 ;;
    esac
done
shift $((OPTIND - 1))

# Make sure we are not inside a container already
[[ -e /proc/1 ]] && grep -q 'cpu:/docker/' /proc/1/cgroup && { echo "Cannot start a container inside another container"; exit 1; }

# Find the docker binary
[[ -z ${DOCKER_BINARY} ]] && { DOCKER_BINARY=$(which docker || true);
    [[ -z ${DOCKER_BINARY} ]] && { DOCKER_BINARY=/usr/local/bin/docker;
        [[ -e ${DOCKER_BINARY} ]] || { DOCKER_BINARY=/usr/bin/docker;
            [[ -e ${DOCKER_BINARY} ]] || { echo "Could not find a docker binary"; exit 1; }
        }
    }
}

# If the user did not supply a command to run, start the container with an interactive shell
if [[ $# -le 0 ]]; then
    cmd="/bin/bash"

# If the user specified a command, run that command in the container
else
    cmd="$*"
fi

# Get the host name and IP
HOSTNAME=$(hostname -s)
if [[ $(uname) == "Darwin" ]]; then
    ORIGINAL_IFS=${IFS}
    IFS=$'\n'
    for service in $(/usr/sbin/networksetup -listnetworkserviceorder | grep '([0123456789])' | cut -d' ' -f2-); do
        HOST_IP=$(/usr/sbin/networksetup -getinfo "${service}" | grep "^IP address" | cut -d' ' -f3 || true)
        [[ -n ${HOST_IP} ]] && break
    done
    IFS=${ORIGINAL_IFS}
else
    for nicpath in /sys/class/net/*; do
        [[ ! -e ${nicpath}/device ]] && continue
        HOST_IP=$(/sbin/ifconfig $(basename ${nicpath}) | /usr/bin/grep inet | /usr/bin/awk '$1=="inet" {print $2}')
    done
fi

# Set up X11 options if X is running
X11_SOCKET=""
X11_DISPLAY=""
if [[ -e /tmp/.X11-unix && -n ${HOST_IP-} ]]; then
    X11_SOCKET="--volume /tmp/.X11-unix:/tmp/.X11-unix"
    X11_DISPLAY="--env DISPLAY=${HOST_IP}:0"
fi

# Find the volumes to mount into the container
eval HOMEDIR="~"

if [[ ${SHARED} -eq 1 ]]; then
    container_id=$("${DOCKER_BINARY}" container ls --format '{{.Names}}' | grep ${LINUX_SHELL_CONTAINER_NAME} | awk '{print $1}' | tail -n1 || echo "")
    # Start a new container if there is not one already running
    if [[ -z ${container_id} ]]; then
        # See if the container exists but is not started
        container_id=$("${DOCKER_BINARY}" container ls --all --format '{{.Names}}' | grep ${LINUX_SHELL_CONTAINER_NAME} | tail -n1 || echo "")
        if [[ -n ${container_id} ]]; then
            "${DOCKER_BINARY}" container start ${container_id} &>/dev/null
        else
            container_id=$("${DOCKER_BINARY}" container run \
                                --tty \
                                --privileged \
                                --detach \
                                --env DOCKER_HOST_NAME=${HOSTNAME} \
                                --env DOCKER_HOST_IP=${HOST_IP} \
                                --env DOCKER_HOST_USER=${USER} \
                                ${X11_DISPLAY} \
                                ${X11_SOCKET} \
                                --volume ${HOMEDIR}:/root \
                                --volume /var/run/docker.sock:/var/run/docker.sock \
                                --workdir /root \
                                --hostname ${LINUX_SHELL_CONTAINER_NAME}1 \
                                --name ${LINUX_SHELL_CONTAINER_NAME}1 \
                                ${LINUX_SHELL_RUN_OPTIONS} \
                                ${LINUX_SHELL_IMAGE_NAME})
        fi
    fi

    # Join the existing container
    exec "${DOCKER_BINARY}" container exec \
            --tty \
            --interactive \
            --privileged \
            --env DOCKER_HOST_NAME=${HOSTNAME} \
            --env DOCKER_HOST_IP=${HOST_IP} \
            --env DOCKER_HOST_USER=${USER} \
            ${X11_DISPLAY} \
            ${container_id} \
            ${cmd}

else
  # Find any other existing containers to give this one a unique name
  index=$("${DOCKER_BINARY}" container ls --all --format '{{.Names}}' | grep ${LINUX_SHELL_CONTAINER_NAME} | cut -d- -f3 | sort | tail -n1 || echo 0)
  (( index++ )) || true

  # Start the container.  To make it as seamless as possible:
  #   Run in privileged mode so the user has max power
  #   Export DOCKER_HOST_USER, DOCKER_HOST_NAME and DOCKER_HOST_IP so that the container knows a little bit about its parent
  #   Mount the current user's home directory into the container so they get the same environment
  #   Mount the X11 socket and export DISPLAY so that GUI apps can run in the container

  exec "${DOCKER_BINARY}" container run \
      --interactive \
      --tty \
      --privileged \
      --rm \
      --env DOCKER_HOST_NAME=${HOSTNAME} \
      --env DOCKER_HOST_IP=${HOST_IP-} \
      --env DOCKER_HOST_USER=${USER-} \
      ${X11_DISPLAY} \
      ${X11_SOCKET} \
      --volume ${HOMEDIR}:/root \
      --volume /var/run/docker.sock:/var/run/docker.sock \
      --workdir /root \
      --hostname ${LINUX_SHELL_CONTAINER_NAME}${index} \
      --name ${LINUX_SHELL_CONTAINER_NAME}${index} \
      ${LINUX_SHELL_RUN_OPTIONS} \
      ${LINUX_SHELL_IMAGE_NAME} \
      ${cmd}
fi
