#!/bin/bash

echo "Executing build hook"

docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) \
             --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
             --build-arg VERSION=$(cat .container-version) \
             --tag ${IMAGE_NAME} \
             .

